spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: ${RABBITMQ_VHOST:fiapx}
    username: ${RABBITMQ_USER:fiapx}
    password: ${RABBITMQ_PASSWORD:fiapx123}
server:
  port: ${SERVER_PORT:8087}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

app:
  notification:
    from-email: ${MAIL_FROM:noreply@fiapx.com}
    notify-on-processed: ${NOTIFY_ON_PROCESSED:true}

logging:
  level:
    br.com.fiap: INFO
    org.springframework: WARN

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8090}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: test
  mail:
    host: localhost
    port: 3025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

---
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: ${RABBITMQ_HOST:fiap-rabbitmq}
  mail:
    host: ${MAIL_HOST:fiap-mailhog}
    port: ${MAIL_PORT:1025}
