version: '3.8'
name: ms-notification

services:

  notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8087
      RABBITMQ_HOST: host.docker.internal
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: fiapx
      RABBITMQ_USER: fiapx
      RABBITMQ_PASSWORD: fiapx123
      AUTH_SERVICE_URL: http://host.docker.internal:8090
      MAIL_HOST: fiap-mailhog
      MAIL_PORT: 1025
      MAIL_FROM: noreply@fiapx.com
      NOTIFY_ON_PROCESSED: "true"
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      NEW_RELIC_APP_NAME: notification-ms-local
    ports:
      - "8087:8087"
    depends_on:
      - mailhog
    networks:
      - app-network
      - fiap-network
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: fiap-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network
      - fiap-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  fiap-network:
    external: true
    name: fiap-network
