apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
        - name: notification-api
          image: notification-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_VHOST
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: MAIL_PORT
            - name: MAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: MAIL_FROM
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: AUTH_SERVICE_URL
            - name: NOTIFY_ON_PROCESSED
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: NOTIFY_ON_PROCESSED
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8087
            initialDelaySeconds: 30
            periodSeconds: 20
