apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: fiapx
spec:
  selector:
    app: notification-api
  ports:
    - name: http
      port: 8087
      targetPort: 8087
  type: ClusterIP
